// Sample job listings data
const JOBS = [
  {
    id: 1,
    title: "Otel Resepsiyonisti",
    company: "Grand Bella Resort",
    companyInitial: "GB",
    location: "Antalya, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "turizm",
    panel: "skilled",
    salary: "₺18.000 – 24.000",
    posted: "2 gün önce",
    desc: "5 yıldızlı resort otelimizde görev yapacak, yabancı dil bilen, müşteri odaklı deneyimli resepsiyonist arıyoruz.",
    lang: "İngilizce, Türkçe",
    experience: "2+ yıl"
  },
  {
    id: 2,
    title: "İnşaat Ustası (Demir)",
    company: "Mega Yapı AŞ",
    companyInitial: "MY",
    location: "İstanbul, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "insaat",
    panel: "skilled",
    salary: "₺22.000 – 30.000",
    posted: "1 gün önce",
    desc: "Büyük ölçekli inşaat projelerimizde çalışacak deneyimli demir ustası aranmaktadır.",
    lang: "Türkçe",
    experience: "5+ yıl"
  },
  {
    id: 3,
    title: "Peyzaj Mimarı",
    company: "Yeşil Bahçe Ltd",
    companyInitial: "YB",
    location: "İzmir, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "bahce",
    panel: "skilled",
    salary: "₺20.000 – 28.000",
    posted: "3 gün önce",
    desc: "Konut projeleri ve kamusal alanlarda bahçe tasarımı yapacak peyzaj mimarı arıyoruz.",
    lang: "Türkçe",
    experience: "3+ yıl"
  },
  {
    id: 4,
    title: "Temizlik Personeli",
    company: "CleanPro Hizmetleri",
    companyInitial: "CP",
    location: "Ankara, Türkiye",
    country: "Türkiye",
    type: "Yarı Zamanlı",
    category: "temizlik",
    panel: "regular",
    salary: "₺12.000 – 15.000",
    posted: "Bugün",
    desc: "Ofis ve iş merkezlerinde görev yapacak temizlik personeli aranmaktadır. Deneyimsiz başvurabilir.",
    lang: "Türkçe",
    experience: "Deneyim gerekmez"
  },
  {
    id: 5,
    title: "Güvenlik Görevlisi",
    company: "SafeGuard AVM",
    companyInitial: "SG",
    location: "İstanbul, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "guvenlik",
    panel: "regular",
    salary: "₺14.000 – 18.000",
    posted: "1 gün önce",
    desc: "AVM kompleksimizde görev yapacak özel güvenlik belgeli personel arıyoruz.",
    lang: "Türkçe",
    experience: "1+ yıl"
  },
  {
    id: 6,
    title: "Depo & Lojistik Elemanı",
    company: "LogiTrans",
    companyInitial: "LT",
    location: "Bursa, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "lojistik",
    panel: "regular",
    salary: "₺13.500 – 16.000",
    posted: "2 gün önce",
    desc: "Depo operasyonlarında görev yapacak, forklift belgeli eleman aranmaktadır.",
    lang: "Türkçe",
    experience: "1+ yıl"
  },
  {
    id: 7,
    title: "Tur Rehberi",
    company: "Discover Türkiye",
    companyInitial: "DT",
    location: "Kapadokya, Türkiye",
    country: "Türkiye",
    type: "Mevsimlik",
    category: "turizm",
    panel: "skilled",
    salary: "₺16.000 – 22.000",
    posted: "4 gün önce",
    desc: "İngilizce ve Rusça bilen, lisanslı profesyonel tur rehberleri arıyoruz.",
    lang: "İngilizce, Rusça",
    experience: "2+ yıl"
  },
  {
    id: 8,
    title: "Tarım İşçisi",
    company: "EkoTarım Çiftliği",
    companyInitial: "ET",
    location: "Manisa, Türkiye",
    country: "Türkiye",
    type: "Mevsimlik",
    category: "tarim",
    panel: "regular",
    salary: "₺600/gün",
    posted: "Bugün",
    desc: "Üzüm hasadı sezonunda çalışacak tarım işçileri aranmaktadır. Konaklama sağlanır.",
    lang: "Türkçe",
    experience: "Deneyim gerekmez"
  },
  {
    id: 9,
    title: "Sağlık Teknikeri",
    company: "MedCare Klinik",
    companyInitial: "MC",
    location: "Gaziantep, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "saglik",
    panel: "skilled",
    salary: "₺25.000 – 32.000",
    posted: "1 gün önce",
    desc: "Kliniklerimizde çalışacak, mezun tıbbi laboratuvar teknisyeni veya sağlık teknikeri arıyoruz.",
    lang: "Türkçe, İngilizce",
    experience: "2+ yıl"
  },
  {
    id: 10,
    title: "Yazılım Geliştirici",
    company: "TechVision A.Ş.",
    companyInitial: "TV",
    location: "İstanbul (Uzaktan)",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "teknoloji",
    panel: "skilled",
    salary: "₺45.000 – 70.000",
    posted: "3 gün önce",
    desc: "React ve Node.js konusunda deneyimli, takım çalışmasına yatkın full-stack geliştirici arıyoruz.",
    lang: "Türkçe, İngilizce",
    experience: "3+ yıl"
  },
  {
    id: 11,
    title: "Fırın Ustası",
    company: "Lezzet Fırınları",
    companyInitial: "LF",
    location: "İzmir, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "gida",
    panel: "regular",
    salary: "₺15.000 – 19.000",
    posted: "2 gün önce",
    desc: "Zincir fırınlarımızda çalışacak deneyimli fırın ustası ve yardımcıları aranmaktadır.",
    lang: "Türkçe",
    experience: "2+ yıl"
  },
  {
    id: 12,
    title: "İnşaat Proje Yöneticisi",
    company: "Atlas İnşaat",
    companyInitial: "AI",
    location: "İstanbul, Türkiye",
    country: "Türkiye",
    type: "Tam Zamanlı",
    category: "insaat",
    panel: "skilled",
    salary: "₺55.000 – 80.000",
    posted: "Bugün",
    desc: "Büyük konut projelerinde liderlik edecek, deneyimli inşaat mühendisi/proje yöneticisi arıyoruz.",
    lang: "Türkçe, İngilizce",
    experience: "7+ yıl"
  }
];

const CATEGORIES_SKILLED = [
  { id: "turizm",     icon: "🏨", name: "Turizm",       count: 342 },
  { id: "insaat",     icon: "🏗️", name: "İnşaat",       count: 218 },
  { id: "bahce",      icon: "🌿", name: "Bahçe İşleri", count: 96  },
  { id: "saglik",     icon: "🏥", name: "Sağlık",       count: 187 },
  { id: "teknoloji",  icon: "💻", name: "Teknoloji",    count: 253 },
  { id: "tarim",      icon: "🌾", name: "Tarım",        count: 74  },
  { id: "enerji",     icon: "⚡", name: "Enerji",       count: 58  },
  { id: "hukuk",      icon: "⚖️", name: "Hukuk",        count: 43  },
];

const CATEGORIES_REGULAR = [
  { id: "temizlik",   icon: "🧹", name: "Temizlik",        count: 289 },
  { id: "guvenlik",   icon: "🛡️", name: "Güvenlik",        count: 176 },
  { id: "lojistik",   icon: "🚚", name: "Depo & Lojistik", count: 201 },
  { id: "tarim",      icon: "🌾", name: "Tarım",           count: 153 },
  { id: "gida",       icon: "🍽️", name: "Gıda & Restoran", count: 212 },
  { id: "tekstil",    icon: "👗", name: "Tekstil",         count: 98  },
  { id: "kargo",      icon: "📦", name: "Kargo & Dağıtım", count: 134 },
  { id: "uretim",     icon: "🏭", name: "Üretim",          count: 167 },
];

const INVESTOR_PROJECTS = [
  {
    id: 1,
    category: "Turizm & Otelcilik",
    title: "5 Yıldızlı Resort Projesi",
    location: "Antalya, Türkiye",
    budget: "€12 Milyon",
    roi: "%18 / yıl",
    duration: "36 ay",
    status: "Açık",
    desc: "Akdeniz kıyısında inşa edilecek 350 odalı lüks resort. Personel istihdamı ve operasyon yönetimi A&D Global Work güvencesiyle.",
    colorClass: ""
  },
  {
    id: 2,
    category: "İnşaat & Gayrimenkul",
    title: "Rezidans Konut Kompleksi",
    location: "İstanbul, Türkiye",
    budget: "€28 Milyon",
    roi: "%22 / yıl",
    duration: "48 ay",
    status: "Açık",
    desc: "İstanbul Avrupa yakasında 450 daireli modern konut projesi. Nitelikli işçi tedariki garantili.",
    colorClass: "--blue"
  },
  {
    id: 3,
    category: "Tarım & Teknoloji",
    title: "Akıllı Tarım Çiftliği",
    location: "Konya, Türkiye",
    budget: "€4,5 Milyon",
    roi: "%15 / yıl",
    duration: "24 ay",
    status: "Açık",
    desc: "Drone ve IoT teknolojisiyle donatılmış 500 hektarlık akıllı tarım projesi. Çalışan eğitimi dahil.",
    colorClass: "--green"
  },
  {
    id: 4,
    category: "Enerji",
    title: "Güneş Enerji Santrali",
    location: "Şanlıurfa, Türkiye",
    budget: "€8 Milyon",
    roi: "%20 / yıl",
    duration: "18 ay",
    status: "Açık",
    desc: "50 MW kapasiteli güneş enerji santrali kurulum ve işletme projesi. Teknik personel temini dahil.",
    colorClass: ""
  },
];
